### ISSUE TITLE
add 3d animation

### ISSUE THREAD

**Issue by pietro909** [3DWeb-cc/webgl-website#1]
as per our discussion, a quick reminder:
- webgl based
- using particle system
- animated
- cool (?)

nice to have: **user interaction**

**Comment by gsambrotta** [comment]
So, are you going to take this issue or I do it?
In case, any suggestions how to do it/which animation take?

**Comment by pietro909** [comment]
yep, I'm going to make it today!

**Comment by gsambrotta** [comment]
Coolio! Let me know if you need help :)

**Comment by pietro909** [comment]
added in 8a8cbf63160d53e63af0d4181f1b562dd3c87ba0
